windsorcli/cli

internal/config/config.go, internal/config/defaults.go, internal/services/talos_controlplane_service.go, internal/services/talos_controlplane_service_test.go, internal/services/talos_worker_service.go, internal/services/talos_worker_service_test.go, internal/virt/docker_virt.go
The config object is now dynamically populate with a value for nodes, e.g.,
```
cluster:
controlplanes:
...
nodes:
controlplane-1:
hostname: controlplane-1.test
node: 10.5.0.3
endpoint: 10.5.0.3:50000
workers:
...
nodes:
worker-1:
hostname: worker-1.test
node: 10.5.0.13
endpoint: 10.5.0.13:50000
```
This will help support templating in upcoming work.
=> Extend config to include node info

.github/renovate.json, .github/workflows/ci.yaml, aqua.yaml
Adds aqua to manage our local CLI tools. We'll leave `.tool-versions` in for a little while.
=> Add aqua for tool management

aqua.yaml, pkg/virt/docker_virt.go, pkg/virt/docker_virt_test.go, pkg/virt/shims.go
Docker compose may be installed in a variety of ways, and be called differently depending on the system. This fix implements a change that tries to determine the correct one to use before calling it.
=> Fix docker-compose call

pkg/controller/mock_controller.go, pkg/controller/mock_controller_test.go, pkg/controller/real_controller.go, pkg/controller/real_controller_test.go, pkg/env/docker_env.go, pkg/env/docker_env_test.go, pkg/env/shims.go
This fixes an issue related to the `DOCKER_HOST` not being set, and thus causing issues connecting to the Docker daemon. Additionally, environment variables were also often not being print fully when encountering an issue with aws. Now, both the docker env and aws env components won't be created if not enabled.
=> Fix docker host and aws var issue

pkg/env/docker_env.go, pkg/env/docker_env_test.go
We don't really need to inject `COMPOSE_FILE` automatically. It interferes with the ability to just run docker-compose directly.
=> Don't inject COMPOSE_FILE

go.mod, go.sum, pkg/services/dns_service.go, pkg/services/talos_controlplane_service.go, pkg/services/talos_worker_service.go, pkg/shell/shell.go
When service definitions in a docker-compose file are anonymous, containers are restarted on every `docker-compose up`. Consequently, our talos nodes were restarting. To fix this, we need to generate named volumes.
=> Fix restarting nodes on second `windsor up`

pkg/blueprint/blueprint_v1alpha1.go, pkg/blueprint/templates/local.jsonnet, pkg/generators/terraform_generator.go
Adds the gitops/flux template to the `local.jsonnet` file. This allow for bootstrapping a gitops operator on to the cluster.
=> Add gitops/flux to local.jsonnet

pkg/blueprint/blueprint_v1alpha1.go, pkg/blueprint/blueprint_v1alpha1_test.go
The blueprint yaml was being merged improperly and messing up existing content. This change enhances the merge logic so that it prefers the existing `blueprint.yaml` terraform components and ordering. This makes it so the routine will seldom modify existing `blueprint.yaml` files inappropriately.
=> Fix blueprint terraform component merge logic

api/v1alpha1/blueprint_types.go, api/v1alpha1/blueprint_types_test.go, pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/blueprint/defaults.go, pkg/blueprint/mock_blueprint_handler.go, pkg/blueprint/mock_blueprint_handler_test.go, pkg/generators/generator_test.go, pkg/generators/terraform_generator.go, pkg/generators/terraform_generator_test.go, pkg/stack/stack_test.go
Properly organizes the blueprint type in to an api folder, in line with common practices
=> Reorg blueprint types => api/ folder

pkg/blueprint/templates/local.jsonnet, pkg/config/defaults.go, pkg/controller/real_controller.go, pkg/services/dns_service.go, pkg/services/dns_service_test.go, pkg/services/mock_service.go, pkg/services/mock_service_test.go, pkg/services/registry_service.go, pkg/services/registry_service_test.go, pkg/services/service.go, pkg/services/service_test.go
Registry mirrors were reversed in the Talos machine config. This fixes that, but also introduces a `GetHostname` function that allows us to transform things like `ghcr.io` => `ghcr.test` based on use case.
=> Corrected registry mirrors

pkg/constants/constants.go
We now build and push our git-livereload image to windsorcli/git-livereload, this changes the reference.
=> Update git-livereload image reference

docs/install.md
Updates the instructions on Windows to include a note about running PowerShell as an administrator, and being sure to create the `C:\Program Files\Windsor` folder.
=> Fix windows installation instructions

pkg/blueprint/blueprint_handler.go
When applying kustomizations, neither `components` nor `patches` were being included.
=> Include patches and components when generating kustomization

.vscode/launch.json, api/v1alpha1/cluster/cluster_config.go, api/v1alpha1/cluster/cluster_config_test.go, docs/reference/configuration.md, pkg/config/config_handler.go, pkg/config/defaults.go, pkg/config/mock_config_handler.go, pkg/config/mock_config_handler_test.go, pkg/config/yaml_config_handler.go, pkg/config/yaml_config_handler_test.go, pkg/services/talos_worker_service.go, pkg/services/talos_worker_service_test.go
It's now possible to set nodeports on workers as follows:
```
contexts:
local:
cluster:
nodeports:
- 8080:30080/tcp
- 8443:30443/tcp
```
=> Worker nodeports

pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go
The blueprint configmap now includes the `CONTEXT` value. This can now be referred to in k8s manifests as `${CONTEXT}`.
=> Include CONTEXT value in configmap

api/v1alpha1/config_types_test.go, api/v1alpha1/docker/docker_config.go, api/v1alpha1/utils.go, docs/reference/configuration.md, pkg/network/colima_network.go, pkg/network/colima_network_test.go, pkg/network/darwin_network.go, pkg/network/darwin_network_test.go, pkg/network/linux_network.go, pkg/network/linux_network_test.go, pkg/network/network.go, pkg/network/network_test.go, pkg/network/windows_network.go, pkg/network/windows_network_test.go, pkg/services/talos_service.go, pkg/services/talos_service_test.go, pkg/virt/docker_virt.go, pkg/virt/docker_virt_test.go
Port assignment, specifically port mappings between the "docker desktop" and "colima" drivers, was beginning to cause issues. The colima driver was breaking on `windsor up` when assigning more than one worker node.
In particular, we don't want to increment port assignments unless we're in "localhost" mode. Unless. we are assigning `nodeports` in which case we do want to increment host port values.
Also includes some necessary follow-up from a previous PR involving networking config changes.
=> Improve port assignment between virt options

api/v1alpha1/docker/docker_config.go, api/v1alpha1/docker/docker_config_test.go, cmd/env.go, cmd/env_test.go, pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/constants/constants.go, pkg/env/docker_env.go, pkg/env/docker_env_test.go, pkg/services/dns_service.go, pkg/services/registry_service.go, pkg/services/registry_service_test.go, pkg/services/service.go, pkg/services/service_test.go, pkg/services/talos_service.go
The `REGISTRY_URL` environment variable is now injected in to the environment automatically when a local registry is available. Furthermore, this variable is made available to all kustomizations as a post-rendered value.
=> REGISTRY_URL environment variable

cmd/check.go, cmd/context.go, cmd/down.go, cmd/env.go, cmd/env_test.go, cmd/exec.go, cmd/hook.go, cmd/init.go, cmd/init_test.go, cmd/install.go, cmd/root.go, cmd/root_test.go, cmd/up.go
Passes the controller via Cobra's context vs. setting it globally. This improves the architecture to allow for the controller to be more cleanly injected, improving testability.
=> Pass controller through cli context

pkg/blueprint/templates/local.jsonnet
Kustomize components need to reference `source: core`.
=> Default blueprints reference core source

api/v1alpha1/cluster/cluster_config.go, api/v1alpha1/cluster/cluster_config_test.go, cmd/down.go, cmd/down_test.go, cmd/shims.go, pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/blueprint/templates/local.jsonnet, pkg/config/defaults.go, pkg/config/yaml_config_handler_test.go, pkg/env/kube_env.go, pkg/env/kube_env_test.go, pkg/env/shims.go, pkg/services/talos_service.go, pkg/services/talos_service_test.go
With the addition of windsorcli/core#116 it's now possible to create HostPath style persistent volumes. This feature is now supported by the CLI. `PV_<NAMESPACE>_<NAME>` env vars are introduced that point to local paths that correspond to volumes in the cluster.
=> Support for local volume storage driver

.vscode/launch.json, cmd/install.go, cmd/install_test.go, pkg/env/kube_env_test.go
The `REGISTRY_URL` was not being injected properly in to post-build args. This was due to not creating resources necessary to infer this value in the local environment if not explicitly set.
=> Fix missing registry url

pkg/blueprint/templates/local.jsonnet
We do not need to ignore the `eth0` interface if running docker directly on linux.
=> Don't ignore eth0 on docker

pkg/config/config_handler.go, pkg/config/mock_config_handler.go, pkg/config/mock_config_handler_test.go, pkg/config/yaml_config_handler.go, pkg/config/yaml_config_handler_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/mock_controller.go, pkg/controller/mock_controller_test.go, pkg/controller/real_controller.go, pkg/env/custom_env.go, pkg/env/custom_env_test.go
We have the `environment` configuration but hadn't fully implemented a handler for it that printed the env vars. This implements the `custom env` handler, allowing the user to add or override any environment variable on a per-context basis.
=> Implement custom env printer

pkg/virt/docker_virt.go, pkg/virt/docker_virt_test.go
If a compose command isn't found, it doesn't need to throw an error, it just doesn't need to set it. This allows us to perform `windsor check` without triggering an error.
=> Don't throw error when determining compose command

pkg/services/localstack_service.go, pkg/services/localstack_service_test.go
Fixes the localstack pro configuration by configuring it as an environment variable vs. a docker-compose "secret"
=> Fix localstack pro configuration

api/v1alpha1/aws/aws_config.go, api/v1alpha1/aws/aws_config_test.go, api/v1alpha1/config_types_test.go, aqua.yaml, go.mod, pkg/config/yaml_config_handler_test.go, pkg/constants/constants.go, pkg/controller/mock_controller.go, pkg/controller/real_controller.go, pkg/di/mock_injector.go, pkg/env/aws_env.go, pkg/env/aws_env_test.go, pkg/generators/aws_generator.go, pkg/generators/aws_generator_test.go, pkg/generators/shims.go, pkg/services/localstack_service.go
Creates the `.aws/config` file automatically based on config in `windsor.yaml`, in particular `aws.localstack`. A user should now be able to enable localstack in their environment, and run `aws` cli commands once the environment is available.
=> Auto-configure AWS config for localstack

.gitignore, pkg/di/mock_injector_test.go, pkg/env/shims.go, pkg/env/terraform_env.go, pkg/env/terraform_env_test.go, pkg/generators/git_generator.go, pkg/generators/git_generator_test.go, pkg/services/localstack_service.go, pkg/services/localstack_service_test.go
When localstack is enabled locally, it's necessary to provide a special configuration for the AWS provider such that endpoints for various AWS services are configured to point to localstack. This PR introduces this feature in the same manner as the existing `backend_override.tf` approach. Now, a `provider_override.tf` also gets generated if localstack is enabled.
=> Generate AWS terraform provider override when localstack is enabled

.github/renovate.json, .github/workflows/ci.yaml, Dockerfile, aqua.docker.yaml, aqua.yaml, docker-compose.yml
Includes a new Dockerfile that builds the windsor cli and makes it available via a containerized image. This also installs the required toolchain dependencies.
This image uses an entrypoint `windsor exec --`. This means that anything passed to `docker run` will be executed within a windsor context.
The necessary actions are also included for uploading the image to ghcr using a multi-arch build.
=> Windsor docker image

.goreleaser.yaml, docs/install.md
Reconfigure goreleaser to add signing the actual binaries.
=> Sign binaries

pkg/services/dns_service.go, pkg/services/dns_service_test.go, pkg/services/localstack_service.go, pkg/services/localstack_service_test.go, pkg/services/mock_service.go, pkg/services/mock_service_test.go, pkg/services/service.go, pkg/services/service_test.go
Some services now allow wildcard DNS. For example, `*.aws.test` can now accept requests for s3 subdomains.
=> Wildcard service DNS entries

api/v1alpha1/terraform/terraform_config.go, api/v1alpha1/terraform/terraform_config_test.go, pkg/env/terraform_env.go, pkg/env/terraform_env_test.go
Adds a configuration value that allows for prefixing Terraform state backends. This can be done by setting `terraform.backend.prefix`.
This implements the prefix uniquely across `s3`, `kubernetes`, and `local` backends.
=> Terraform state key prefix

Dockerfile, aqua.docker.yaml
The purpose of the Windsor image is to ensure that everything required to build / deploy the local workstation is available. If a user needs these additional tools, they can install them on their own and run them locally.
This PR removes these unnecessary tools.
=> Remove extra tools from Docker image

cmd/exec_test.go, cmd/root.go, pkg/shell/docker_shell.go, pkg/shell/docker_shell_test.go
The docker shell can now be called with ExecProgress as we can with the default shell. This allows for an abbreviated command output with regular updates when executing commands in this mode.
=> DockerShell ExecProgress

pkg/constants/constants.go, pkg/network/darwin_network.go, pkg/network/darwin_network_test.go, pkg/network/linux_network.go, pkg/network/network.go, pkg/network/network_test.go, pkg/network/windows_network.go, pkg/network/windows_network_test.go, pkg/services/dns_service.go, pkg/services/dns_service_test.go, pkg/services/mock_service.go, pkg/services/mock_service_test.go, pkg/services/registry_service.go, pkg/services/registry_service_test.go, pkg/services/service.go, pkg/services/service_test.go, pkg/services/talos_service.go, pkg/services/talos_service_test.go, pkg/services/windsor_service.go, pkg/services/windsor_service_test.go, pkg/shell/docker_shell_test.go, pkg/stack/windsor_stack.go, pkg/stack/windsor_stack_test.go, pkg/virt/docker_virt.go
The local coredns service now creates two networks when we are running in container execution mode. The reason this is necessary is to allow for handling DNS when routing requests from within the Docker network.
=> Run dual DNS servers when running in container exec mode

pkg/constants/constants.go, pkg/env/terraform_env.go, pkg/env/terraform_env_test.go, pkg/env/windsor_env.go, pkg/shell/docker_shell.go, pkg/shell/docker_shell_test.go, pkg/shell/shell_test.go, pkg/shell/unix_shell.go, pkg/shell/windows_shell.go, pkg/stack/stack.go, pkg/stack/stack_test.go, pkg/stack/windsor_stack.go, pkg/stack/windsor_stack_test.go
Previously, terraform commands executed during `windsor up` did not execute inside the container execution environment. This updates this to shift to using it when available.
=> Execute windsor up via container exec mode when applicable

pkg/constants/constants.go
Two DNS servers now run and support selective wildcard DNS. This capability is triggered when we're using the windsor exec environment, so that the windsor container can leverage its DNS internally.
=> Support for dual DNS servers

cmd/context.go, cmd/context_test.go, cmd/env.go, cmd/env_test.go, pkg/config/config_handler.go, pkg/env/windsor_env.go, pkg/env/windsor_env_test.go, pkg/shell/docker_shell_test.go, pkg/shell/mock_shell.go, pkg/shell/mock_shell_test.go, pkg/shell/shell.go, pkg/shell/shell_test.go, pkg/shell/shims.go, pkg/shell/unix_shell.go, pkg/shell/unix_test.go, pkg/shell/windows_test.go
Implements the `WINDSOR_SESSION_TOKEN`. This token is unique to a particular session. When changing contexts or exiting a windsor project, the session token is cleared or updated.
=> Windsor Session ID

pkg/env/kube_env.go, pkg/env/kube_env_test.go
Ansible uses `K8S_AUTH_KUBECONFIG` to set its path to the kubeconfig file. We'd like to support Ansible if it's being used, so this variable should be set.
=> Add K8S_AUTH_KUBECONFIG

pkg/blueprint/templates/default.jsonnet
We moved platform from `<context>.platform` => `<context>.cluster.platform`. We needed to fix one reference in the blueprint jsonnet.
=> Use cluster.platform in the blueprint jsonnet

cmd/down.go, cmd/down_test.go, cmd/init.go, cmd/init_test.go, cmd/install.go, cmd/install_test.go, cmd/up.go, cmd/up_test.go, pkg/controller/controller.go
We don't always want to implicitly load environment variables in to the running process. In order to handle environment cache properly, this should not occur during `windsor env`, for instance. This PR moves the internal environment injection routine in to the appropriate commands and out of the broader `InitializeComponents` method.
=> Selectively load env vars internally

cmd/context.go, cmd/context_test.go, pkg/env/shims.go, pkg/env/windsor_env.go, pkg/env/windsor_env_test.go
The `WINDSOR_SESSION_TOKEN` is a session token that will be used to facilitate further encapsulation of the environment. It uses a session invalidation file to refresh the token on `windsor context set`. Additionally, new shell sessions get their own unique session token.
=> Include WINDSOR_SESSION_TOKEN

cmd/init.go, cmd/init_test.go, go.mod, go.sum, pkg/env/docker_env.go, pkg/env/docker_env_test.go
Previously, we were not re-printing the `DOCKER_HOST` environment variable. This prevented our internally managed defaults to not function at all, so for environments like Colima, it would often not be properly configured to use the appropriate docker socket file.
Also ensures to write the reset token on `windsor init`, which causes the `DOCKER_HOST` environment variable to be reset appropriately.
=> Always print DOCKER_HOST

pkg/network/darwin_network.go, pkg/network/darwin_network_test.go, pkg/network/linux_network.go, pkg/network/linux_network_test.go, pkg/network/network.go, pkg/network/network_test.go, pkg/network/windows_network.go, pkg/network/windows_network_test.go, pkg/services/dns_service.go, pkg/services/dns_service_test.go, pkg/services/registry_service.go, pkg/services/registry_service_test.go, pkg/services/service.go, pkg/services/service_test.go, pkg/services/talos_service.go, pkg/services/talos_service_test.go, pkg/virt/docker_virt.go, pkg/virt/docker_virt_test.go
Since we operate CoreDNS amongst our local development services, it seems reasonable to use it as our docker network DNS. This will eventually allow us to define hostnames and domain routing independently.
The code changes to make this possible are co-dependent on how we generate and template values in our default blueprints. As such, we now also use DNS names instead of IPs for looking up our nodes.
=> Use CoreDNS in docker network and for node endpoints

cmd/root.go, cmd/root_test.go
If we're not in a trusted folder, or haven't yet run windsor init , then many windsor commands simply do not execute. This PR issues a warning to the user.
=> Warn when not in a trusted directory

api/v1alpha1/cluster/cluster_config.go, api/v1alpha1/cluster/cluster_config_test.go, pkg/constants/constants.go, pkg/services/talos_service.go, pkg/services/talos_service_test.go
Allows specifying the cluster node image to use. This specification cascades from the cluster level to the node groups and nodes. Additionally updated to use constants for talos api port.
=> Allow cluster image specification

pkg/config/config_handler.go, pkg/config/mock_config_handler.go, pkg/config/mock_config_handler_test.go, pkg/config/yaml_config_handler.go, pkg/config/yaml_config_handler_test.go
LoadConfigString is used to load YAML directly in to the config structure. This will allow a cleaner test setup in the future.
=> Add LoadConfigString

pkg/services/dns_service.go, pkg/services/dns_service_test.go, pkg/services/talos_service.go, pkg/services/talos_service_test.go
The direction of using split DNS turned out to be dubious. There was a case in which the internal IPs were being reported to the host, even when in localhost mode. This mode has been removed.
Additionally, the talos service needed to be updated to no longer expect a DNS oriented configuration.
=> Remove split DNS

.github/workflows/ci.yaml
Tagging with a post-fix on a semantic version will now trigger a prerelease build.
=> Simple prerelease mechanism

pkg/tools/tools_manager.go, pkg/tools/tools_manager_test.go
Talosctl is not technically required by windsor so is removed from the check.
=> Remove talosctl requirement

.github/release-drafter.yml, .github/workflows/ci.yaml, .goreleaser.yaml
This disables packaging and shipping homebrew when we run goreleaser. Also includes a small change to make Dependencies collapse on the release page.
=> Stop prerelease shipping to homebrew

api/v1alpha1/config_types.go, api/v1alpha1/config_types_test.go, pkg/config/config_handler.go, pkg/config/mock_config_handler.go, pkg/config/mock_config_handler_test.go, pkg/config/shims.go, pkg/config/yaml_config_handler.go, pkg/config/yaml_config_handler_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/env/terraform_env.go, pkg/env/terraform_env_test.go
A context ID is now generated for a context. This value is prefixed with `w` and followed by 7 random lowercase alphanumeric characters. It is automatically written to the `windsor.yaml` config file.
The context ID is available to all Terraform components via the `TF_VAR_context_id` variable.
=> Include a context ID

pkg/generators/generator_test.go, pkg/generators/terraform_generator.go, pkg/generators/terraform_generator_test.go
Makes the generation of Terraform shims more resilient. Specifically involved using `terraform init -backend=false -json` so that we don't throw errors related to backend migration, and output json for more explicit parsing of the response.
=> Terraform shim generation improvements

.github/workflows/ci.yaml, .goreleaser.yaml, api/v1alpha1/config_types.go, api/v1alpha1/config_types_test.go, pkg/config/config_handler.go, pkg/config/mock_config_handler.go, pkg/config/mock_config_handler_test.go, pkg/config/shims.go, pkg/config/yaml_config_handler.go, pkg/config/yaml_config_handler_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/env/terraform_env.go, pkg/env/terraform_env_test.go
Windsor CLI now publishes to Chocolatey.
=> Chocolatey

pkg/env/terraform_env.go, pkg/env/terraform_env_test.go
When setting `terraform.backend: none` in the `windsor.yaml`, no `backend_override.tf` will be created.
=> Terraform backend can be set to "none"

api/v1alpha1/azure/azure_config.go, api/v1alpha1/azure/azure_config_test.go, api/v1alpha1/config_types.go, api/v1alpha1/config_types_test.go, pkg/controller/controller.go, pkg/controller/mock_controller.go, pkg/env/azure_env.go, pkg/env/azure_env_test.go, pkg/generators/git_generator.go, pkg/generators/git_generator_test.go
Adds support for configuring context specific data for an Azure profile / context, such that you can configure a section in `windsor.yaml` as follows:
```
contexts:
production:
azure:
enabled: true
subscription_id: your-subscription-id
tenant_id: your-tenant-id
```
This results in the followig env vars on the context:
```
export ARM_SUBSCRIPTION_ID="your-subscription-id"
export ARM_TENANT_ID="your-tenant-id"
export AZURE_CONFIG_DIR="/path/to/contexts/local/.azure"
export AZURE_CORE_LOGIN_EXPERIENCE_V2="false"
```
To log in to Azure, if you are on a context, all that is required is `az login`. You will be prompted to log in via the SSO flow locally. In automated contexts, it's expected to use more automated methods including OIDC, etc.
=> Azure environment printer

api/v1alpha1/terraform/terraform_config.go, pkg/env/terraform_env.go, pkg/env/terraform_env_test.go
Adds support for the azurerm terraform backend. This backend can be enabled by setting:
```
contexts:
production:
terraform:
backend:
type: azurerm
azurerm:
storage_account_name: <storage-account-name>
container_name: <container-name>
```
=> AzureRM Terraform Backend

.gitignore, pkg/stack/windsor_stack.go
In windsor, the terraform backend is managed. As such, we don't need the prompts from the terraform tool when state is being migrated. This change fixes broken stacks when changing backends.
=> Automatically migrate state on windsor up

pkg/generators/terraform_generator.go, pkg/generators/terraform_generator_test.go
Previously, the `output.tf` in the terraform shims was incorrectly generated by copying the original. This isn't correct, we need to reference the module's output.
=> Fix terraform shim output.tf generation

.goreleaser.yaml
Some additional config options were altered in the goreleaser config, causing the homebrew publishing mechanism to be performed incorrectly. This reverts these changes to more closely resemble the previously working config.
=> Fix goreleaser homebrew config

pkg/generators/terraform_generator.go, pkg/generators/terraform_generator_test.go
The `variables.tf` that is used in Terraform shims is now generated vs. copied. This allows for a slightly cleaner variables.tf file that doesn't include unnecessary validations, _etc._ that might come with the source module.
=> Generate variables.tf in Terraform shims

pkg/generators/terraform_generator.go, pkg/generators/terraform_generator_test.go
A few edge cases were encountered in which default objects and lists were not always be properly generated when creating `tfvars` defaults. This PR expands support for these cases.
=> Improve generation of terraform maps and lists

api/v1alpha1/azure/azure_config_test.go, api/v1alpha1/blueprint_types.go, api/v1alpha1/blueprint_types_test.go, cmd/down.go, cmd/down_test.go, pkg/blueprint/templates/default.jsonnet, pkg/stack/mock_stack.go, pkg/stack/mock_stack_test.go, pkg/stack/stack.go, pkg/stack/stack_test.go, pkg/stack/windsor_stack.go, pkg/stack/windsor_stack_test.go
The `windsor down` command will now perform a `terraform plan -destroy` and take down terraform resources. If performing a destroy on a particular component isn't desired, setting `destroy: false` on a terraform component will skip destruction of that component.
=> Windsor down destroys terraform

pkg/services/registry_service.go, pkg/services/registry_service_test.go, pkg/services/service.go, pkg/services/service_test.go, pkg/services/talos_service_test.go
Fixes an issue where local DNS inside the container network was not properly resolving containers. This was due to the container name not matching a domain name, like git.test or ghcr.test.
=> Use local dns for container names

api/v1alpha1/blueprint_types.go, api/v1alpha1/blueprint_types_test.go, cmd/install.go, cmd/install_test.go, cmd/up.go, cmd/up_test.go, pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/blueprint/mock_blueprint_handler.go, pkg/constants/constants.go
It is now possible to run:
`windsor install --wait`
or,
`windsor up --wait`
The inclusion of this flag will wait for all kustomizations to complete before returning. It waits for a timeout that includes the longest timeout of all sequential kustomizatation timeouts.
=> Wait flag waits for kustomizations to complete

pkg/blueprint/templates/default.jsonnet, pkg/services/talos_service.go
Includes the hostname of the controlplane to the certsans in the talos machine config. Permits communication with the controlplane from inside the dev container network.
=> Add controlplane hostname to certsans

pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go
Resolves:
```
message: 'kustomization path not found: stat /tmp/kustomization-3255846827/kustomize\policy\base: no such file or directory'
reason: ArtifactFailed
```
=> fix: always use forward slashes in flux kustomizations

pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/constants/constants.go
Adds retries when waiting for flux resources, as these can sometimes fail briefly when bootstrapping. This does not necessarily represent a system failure if the systems eventually recover.
Now while waiting, we will continue to wait through up to 5 failures to make sure the system has a chance to recover.
=> fix: Intermittent wait failure

cmd/init.go, pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/blueprint/mock_blueprint_handler.go, pkg/blueprint/mock_blueprint_handler_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/generators/generator.go, pkg/generators/git_generator.go, pkg/generators/kustomize_generator.go, pkg/generators/kustomize_generator_test.go, pkg/generators/mock_generator.go, pkg/generators/mock_generator_test.go, pkg/generators/terraform_generator.go, pkg/generators/terraform_generator_test.go
Adds a new --reset flag to the init command that performs a clean
initialization by:
- Removing .terraform directory
- Resetting blueprint state
- Cleaning up any cached configurations
- Ensuring a fresh start for all components
This provides users with a way to force a complete reset of their
Windsor environment when needed, particularly useful when:
- Switching between different configurations
- Recovering from corrupted states
- Ensuring clean initialization of all components
=> feat(init): add --reset flag for clean initialization

.github/renovate.json
Ideally this will fix the problem of the endlessly re-opened renovate PRs for indirect dependencies.
=> fix: simplify Renovate config to use default Go module handling

pkg/generators/terraform_generator.go
Adds `-upgrade` when performing the `terraform init` during the module loading phase. Fixes lockfile failures.
=> fix(terraform): add -upgrade flag to terraform init for latest module versions

pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go
This PR fixes issues with kustomization updates by switching to the dynamic client and properly handling suspend states. The previous implementation could fail during updates due to improper resource version handling and would reset suspend states.
Key changes:
- Switch to dynamic client for proper resource version management
- Add proper Group/Version/Resource parsing for API paths
- Ensure atomic get-then-update operations for kustomizations
- Remove redundant REST client code that could cause version conflicts
- Preserve suspend state during kustomization updates
This change ensures that kustomization updates are handled correctly, preventing version conflicts and maintaining proper suspend states during reconciliation.
=> fix(blueprint): Handle kustomization update scenarios correctly

api/v1alpha1/blueprint_types.go, pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_private_test.go, pkg/blueprint/blueprint_handler_test.go
- Use blueprint metadata name as default source for kustomizations and GitRepository resources instead of configHandler context.
- Add Prune field to Kustomization struct and update DeepCopy methods.
- Remove redundant wait for kustomizations in Install method.
- Update getKustomizations to set source to blueprint name if not specified.
=> fix(blueprint): use blueprint name as default source and add Prune field for kustomizations

pkg/secrets/op_cli_secrets_provider.go, pkg/secrets/op_sdk_secrets_provider.go, pkg/secrets/op_sdk_secrets_provider_test.go, pkg/secrets/sops_secrets_provider.go, pkg/shell/mock_shell.go, pkg/shell/mock_shell_test.go, pkg/shell/scrubbing_writer.go, pkg/shell/shell.go, pkg/shell/shell_test.go, pkg/shell/unix_shell_test.go
Prevents secrets from leaking into terminal output when using `--verbose` flag
- Added `RegisterSecret()` method to shell interface
- Secrets providers register actual secret values with shell when resolved
- All shell command output scrubs registered secrets, replacing them with `********`
=> fix(secrets): prevent secret leakage in verbose shell output

pkg/bundler/artifact.go, pkg/bundler/artifact_test.go, pkg/bundler/mock_artifact.go, pkg/bundler/mock_artifact_test.go, pkg/bundler/shims.go
Introduces core artifact creation functionality for packaging blueprint bundles into distributable tar.gz archives.
- ArtifactBuilder (pkg/bundler/artifact.go)
- Creates compressed tar.gz artifacts from prepared file collections
- Embeds comprehensive metadata with git provenance and builder info
- Supports flexible naming via name:version tag format or metadata.yaml
- Handles intelligent output path resolution (directory vs explicit filename)
=> feat(bundler): Add artifact builder foundation

pkg/bundler/bundler.go, pkg/bundler/bundler_test.go, pkg/bundler/mock_bundler.go, pkg/bundler/mock_bundler_test.go, pkg/bundler/shims.go
Introduces the core bundler system foundation. This foundation enables different content types (templates, kustomize, terraform) to contribute files to distributable artifacts through a unified interface.
=> feat(bundler): Add bundler foundation

pkg/bundler/template_bundler.go, pkg/bundler/template_bundler_test.go
Adds the template bundler. The template bundler adds contents in `contexts/_template` to the archive.
=> feat(bundler): Add template bundler

pkg/bundler/kustomize_bundler.go, pkg/bundler/kustomize_bundler_test.go
Adds the kustomize bundler, which packages the `kustomize/` folder in to the archive.
=> feat(bundler): Add kustomize bundler

cmd/bundle.go, cmd/bundle_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go
Adds the `windsor bundle` command. This command generates a combined .tar.gz file that will later be used as an OCI artifact.
=> feat(cmd): Add windsor bundle command

cmd/bundle_test.go, cmd/push_test.go, pkg/blueprint/blueprint_handler.go, pkg/bundler/artifact.go, pkg/bundler/artifact_test.go, pkg/bundler/kustomize_bundler.go, pkg/bundler/kustomize_bundler_test.go, pkg/bundler/mock_artifact.go, pkg/bundler/mock_artifact_test.go, pkg/bundler/template_bundler.go, pkg/bundler/template_bundler_test.go, pkg/bundler/terraform_bundler.go, pkg/bundler/terraform_bundler_test.go, pkg/generators/generator_test.go, pkg/generators/shims.go, pkg/generators/terraform_generator.go, pkg/generators/terraform_generator_test.go
Terraform components listed in the `blueprint.yaml` can now reference sources with OCI registries. This mechanism will extract the terraform modules to a local `.windsor/.oci_extracted` folder before creating the module shims.
Bulk of the line changes are due to massive reordering of the terraform generator tests to match the style guidelines.
=> feat(blueprint): Support OCI sources for terraform components

pkg/pipelines/mock_pipeline.go, pkg/pipelines/mock_pipeline_test.go, pkg/pipelines/pipeline.go, pkg/pipelines/pipeline_test.go, pkg/pipelines/shims.go
The controller has become unwieldy and also is the wrong architecture for a CLI or pipeline utility. The base pipeline begins our migration away from the controller towards a dedicated pipeline approach.
=> refactor(pipeline): Add base pipeline foundation

.cursorrules, cmd/env_test.go
Brings back `env_test.go` which was accidentally deleted.
=> chore(cmd): Re-introduce env tests

cmd/context.go, cmd/context_test.go, pkg/pipelines/context_pipeline.go, pkg/pipelines/context_pipeline_test.go, pkg/pipelines/mock_context_pipeline.go, pkg/pipelines/mock_context_pipeline_test.go
Refactors the `windsor context` command to follow the pipeline architectural pattern.
=> refactor(pipeline): Migrate windsor context to pipeline architecture

cmd/check.go, cmd/check_test.go, cmd/root.go, pkg/pipelines/check_pipeline.go, pkg/pipelines/check_pipeline_test.go, pkg/pipelines/mock_check_pipeline.go, pkg/pipelines/mock_check_pipeline_test.go
Migrates `windsor check` to use the pipeline pattern.
=> refactor(pipeline): Migrate check to pipeline pattern

cmd/root_test.go, pkg/env/env_test.go, pkg/pipelines/env_pipeline.go, pkg/pipelines/env_pipeline_test.go, pkg/pipelines/pipeline_test.go, pkg/shell/mock_shell.go, pkg/shell/mock_shell_test.go, pkg/shell/shell.go, pkg/shell/shell_test.go, pkg/shell/windows_shell_test.go
Adds a `quiet` context parameter to the env pipeline. Permits using the env pipeline only for environment injection in the process in addition to shell injection.
=> refactor(pipeline): Allow env pipeline to run in quiet mode

cmd/check.go, cmd/context.go, cmd/env.go, cmd/exec.go, cmd/hook.go, pkg/pipelines/check.go, pkg/pipelines/check_test.go, pkg/pipelines/context.go, pkg/pipelines/context_test.go, pkg/pipelines/env.go, pkg/pipelines/env_test.go, pkg/pipelines/exec_pipeline.go, pkg/pipelines/exec_pipeline_test.go, pkg/pipelines/hook.go, pkg/pipelines/hook_test.go, pkg/pipelines/mock_pipeline.go, pkg/pipelines/pipeline.go, pkg/pipelines/pipeline_test.go
Include the ctx parameter in a pipeline's Initialize. Context values may impact what a pipeline creates and initializes.
=> refactor(pipeline): Pass context in to initialize

api/v1alpha1/config_types.go, api/v1alpha1/config_types_test.go, pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/config/yaml_config_handler_test.go
Removes the projectName from the config. It's only useful as an option in the blueprint templating context, and usually only by core local blueprints.
=> refactor(config): Remove projectName from config

pkg/generators/git_generator.go, pkg/generators/git_generator_test.go
It is now possible to comment out .gitignore lines added by windsor. If doing so, it will not attempt to rewrite it.
=> fix(generator): Git generator considers commented lines

api/v1alpha1/config_types.go, api/v1alpha1/config_types_test.go, pkg/pipelines/check_test.go, pkg/pipelines/env.go, pkg/pipelines/env_test.go, pkg/pipelines/exec_test.go, pkg/pipelines/hook_test.go, pkg/pipelines/pipeline.go, pkg/pipelines/pipeline_test.go
The pipeline tests weren't following test style approaches common in our other packages. Cleans them up using setup* functions.
=> refactor(pipeline): Use test helpers to DRY up tests

cmd/exec_test.go, pkg/template/jsonnet_template.go, pkg/template/jsonnet_template_test.go, pkg/template/mock_template.go, pkg/template/mock_template_test.go, pkg/template/shims.go, pkg/template/template.go, pkg/template/template_test.go
Adds a new `pkg/template` class. This handles processing templates passed in on a map of relative folder paths. They output the templated data as post-rendered paths, for later processing by generators.
=> refactor(template): Add the foundation template package

pkg/terraform/standard_module_resolver.go, pkg/terraform/standard_module_resolver_test.go
Adds a standard terraform module resolver. This module performs a basic `terraform init` to pull down any standard terraform remote module to the local filesystem.
=> refactor(terraform): Add standard module resolver

cmd/root_test.go, pkg/env/env.go, pkg/env/mock_env.go, pkg/env/mock_env_test.go, pkg/env/terraform_env.go, pkg/env/terraform_env_test.go, pkg/pipelines/env_test.go, pkg/pipelines/init.go, pkg/stack/stack.go, pkg/stack/stack_test.go, pkg/stack/windsor_stack.go, pkg/stack/windsor_stack_test.go
More explicitly injects intended variables in to the terraform commands during a `windsor up` operation. Also uses `-chdir`.
=> Refactor(stack): Explicitly inject terraform vars on windsor up

pkg/env/terraform_env.go, pkg/env/terraform_env_test.go
Fixes an issue in which the `backend_override.tf` file was not being generated during a `windsor down` operation. Related to changes in which we pass explicit paths in during terraform operations.
=> fix(env): Enhance generateBackendOverrideTf to accept custom directory

pkg/env/terraform_env.go, pkg/env/terraform_env_test.go
Forces a state migration. We may dynamically reconfigure backends, or their reconfiguration happens at a higher level of coordination via a `windsor.yaml` configuration value.
=> fix(env): Update Terraform CLI args to include -force-copy option for init command

cmd/install.go, cmd/install_test.go, cmd/up.go, cmd/up_test.go, pkg/pipelines/install.go, pkg/pipelines/install_test.go, pkg/pipelines/pipeline.go, pkg/pipelines/pipeline_test.go, pkg/pipelines/up.go, pkg/pipelines/up_test.go
Migrated the `windsor install` command to use the pipeline architecture. Also modified the `windsor up` pipeline to use this when passing the `--install` flag.
=> refactor(pipeline): Migrate install command to use pipeline structure

cmd/bundle.go, cmd/bundle_test.go
The `windsor bundle ...` command now uses the pipeline architecture.
=> refactor(pipeline): Migrate bundle command to use pipeline structure

cmd/push.go, cmd/push_test.go, cmd/root_test.go
Moved `windsor push` to use the new pipeline architecture.
Also fixed a stray new error in the root_test.go.
=> refactor(pipeline): Migrate push command to pipeline structure

api/v1alpha1/config_types.go, api/v1alpha1/config_types_test.go, cmd/init.go, pkg/config/defaults.go, pkg/config/yaml_config_handler_test.go, pkg/pipelines/init.go, pkg/pipelines/init_test.go
The blueprint field isn't necessarily appropriate as there's no single "blueprint" associated with a given context. We still want to pass in the `--blueprint` flag for future use.
=> refactor(config): Remove Blueprint field from Context

pkg/pipelines/pipeline.go, pkg/pipelines/pipeline_test.go
The context wasn't being set during commands such as `windsor init <context>`. Now, if `contextName` is provided to a pipeline, it will be set in the base Initialize function.
=> fix(pipeline): Set context if provided

pkg/blueprint/templates/aws.jsonnet, pkg/blueprint/templates/azure.jsonnet, pkg/blueprint/templates/local.jsonnet, pkg/blueprint/templates/metal.jsonnet, pkg/pipelines/install.go, pkg/pipelines/install_test.go
The `windsor install` command failed to install kustomizations. This was due to both embedded blueprint formatting and the lack of running the `blueprint.LoadConfig` command during init.
=> fix(pipeline): Ensure 'install' deploys kustomizations

pkg/services/dns_service.go, pkg/services/dns_service_test.go, pkg/services/service_test.go, pkg/services/shims.go
Sometimes, the `Corefile/` gets created as a folder. It's still TBD why this happens, but it may be a file I/O issue with concurrent writes to the same location. Either way, this cleans it up if it appears.
=> fix(service): Remediate Corefile written as a folder

pkg/generators/terraform_generator.go, pkg/generators/terraform_generator_test.go
The `windsor init --reset` flag was not overwiting `tfvars` files. Added the correct logic to handle this.
=> fx(generator): Properly overwrites tfvars when --reset is passed

cmd/up.go, pkg/pipelines/init.go
When running `windsor init aws --provider aws` followed by `windsor up`, the system incorrectly loaded Talos cluster components instead of AWS EKS components, despite the configuration showing correct provider settings.
Correctly loads the context if not on `local` by default.
=> fix(pipeline): Fix init pipeline context determination for up/down commands

pkg/template/jsonnet_template.go, pkg/template/jsonnet_template_test.go
A suite of basic helpers for working safely with context values in jsonnet templates. Reduces the amount of code repetition and ensures less chance of panics.
Also includes a processing helper, `baseUrl`.
=> feat(template): Include helpers for jsonnet templating

pkg/config/config_handler.go, pkg/config/mock_config_handler.go, pkg/config/mock_config_handler_test.go, pkg/config/yaml_config_handler.go, pkg/config/yaml_config_handler_test.go, pkg/pipelines/init.go, pkg/pipelines/init_test.go
When performing a `windsor init`, the `windsor.yaml` that's written to the `contexts/` folder will contain all the context configuration. Context specific content will no longer write to the root `windsor.yaml` during initialization.
Also, no longer overwrites the `windsor.yaml` files when passing `--reset`. Windsor configs should remain static, allowing overwriting of other configuration values only.
=> refactor(config): Initialize windsor.yaml to context folder

pkg/constants/constants.go, pkg/services/git_livereload_service.go, pkg/services/git_livereload_service_test.go
Updated constants that enumerate default settings for git-livereload. Now we wish to only include the `kustomize/` folder.
=> fix(livereload): Include kustomize/ folder and don't ignore data/

pkg/config/yaml_config_handler.go, pkg/config/yaml_config_handler_test.go
The new functionality involved in managing a `contexts/<context>/windsor.yaml` was failing to generate if a root `windsor.yaml` already existed. This fixes this functionality to only skip generation of this file if a context is already being configured in the root `windsor.yaml`.
=> fix(config): Generate context windsor config even if root exists

pkg/pipelines/up.go, pkg/pipelines/up_test.go
Sometimes `windsor up` asks for `sudo` permissions or requires administrative privileges in order to configure DNS. The user needs to be notified if local DNS configuration is enabled.
=> feat(pipeline): Show DNS configuration warning on "windsor up"

cmd/env.go, go.mod, pkg/env/aws_env_test.go, pkg/env/azure_env_test.go, pkg/env/docker_env_test.go, pkg/env/env.go, pkg/env/env_test.go, pkg/env/omni_env_test.go, pkg/env/talos_env_test.go, pkg/env/terraform_env_test.go, pkg/env/windsor_env.go, pkg/env/windsor_env_test.go, pkg/pipelines/env.go, pkg/pipelines/env_test.go, pkg/shell/mock_shell.go, pkg/shell/mock_shell_test.go, pkg/shell/shell.go, pkg/shell/unix_shell.go, pkg/shell/unix_shell_test.go, pkg/shell/windows_shell.go, pkg/shell/windows_shell_test.go
The `windsor env` command will now list managed environment variables and their values. It will also list redacted secrets. The corresponding `export` or equivalent is not included in `windsor env` unless `--hook` is passed. This change improves debuggability and makes it simpler to programmatically parse variables by other programs.
Some cleanup of unused helpers in windows shell tests.
=> feat(env): Print simple list of vars when running windsor env

api/v1alpha1/blueprint_types.go, api/v1alpha1/blueprint_types_test.go, pkg/env/shims.go, pkg/env/terraform_env.go, pkg/env/terraform_env_test.go, pkg/pipelines/env.go
Terraform components now include a `dependsOn` field. This can be configured with a list of paths to other terraform components. When specified, output variables from dependencies are injected in to the environment, allowing for variable chaining across TF components.
=> feat(blueprint): Implement dependsOn for terraform components

pkg/secrets/op_cli_secrets_provider.go, pkg/secrets/op_cli_secrets_provider_test.go, pkg/secrets/shims.go
The onepassword CLI secret provider used `shell.ExecSilent`. This function returns output when run via `--verbose`. Because the secret had not yet been retrieved, it was not yet being scrubbed.
The fix is to just use the direct `exec.Command` call, reducing any more code that could introduce such leakages and retreiving the secret directly from the command.
=> fix(secrets): Prevent a secret leak scenario with --verbose

cmd/check.go, cmd/check_test.go, pkg/cluster/cluster_client.go, pkg/cluster/cluster_client_test.go, pkg/kubernetes/kubernetes_client.go, pkg/kubernetes/kubernetes_manager.go, pkg/kubernetes/kubernetes_manager_test.go, pkg/kubernetes/mock_kubernetes_client.go, pkg/kubernetes/mock_kubernetes_client_test.go, pkg/kubernetes/mock_kubernetes_manager.go, pkg/kubernetes/mock_kubernetes_manager_test.go, pkg/pipelines/check.go, pkg/pipelines/check_test.go, pkg/pipelines/pipeline_test.go
It is now possible to run `windsor check node-health --k8s-endpoint` to include a k8s api endpoint health check as part of the node health checks. This will improve control flow for automated routines.
=> feat(check): Include --k8s-endpoint for health checking api endpoint

.github/workflows/ci.yaml, .goreleaser.yaml, pkg/constants/constants.go, pkg/pipelines/init.go, pkg/template/jsonnet_template.go
Pinned releases now automatically pin themselves to the latest semver from the core repository. This mechanism assumes that significant changes to core will always be released before releasing a new version of the CLI. Furthermore, pinned combinations should be tested via integration tests.
=> ci(release): Pin latest core semver on release

pkg/pipelines/init.go, pkg/pipelines/init_test.go
Fixes a couple of related bugs that prevented configuring a correct default `windsor.yaml` file.
=> fix(init): Update setDefaultConfiguration logic for context handling

cmd/check.go, pkg/kubernetes/kubernetes_client.go, pkg/kubernetes/kubernetes_manager.go, pkg/kubernetes/kubernetes_manager_test.go, pkg/kubernetes/mock_kubernetes_client.go, pkg/kubernetes/mock_kubernetes_manager.go, pkg/kubernetes/mock_kubernetes_manager_test.go, pkg/pipelines/check.go, pkg/pipelines/check_test.go, pkg/pipelines/pipeline_test.go
The `windsor check node-health` command can now take a `--ready` flag. This will wait for kubernetes nodes listed in `--nodes` to be in a `Ready` state.
=> feat(check): Check node readiness state

api/v1alpha1/blueprint_types.go, cmd/down.go, pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/kubernetes/kubernetes_client.go, pkg/kubernetes/kubernetes_manager.go, pkg/kubernetes/kubernetes_manager_test.go, pkg/kubernetes/mock_kubernetes_manager.go, pkg/kubernetes/mock_kubernetes_manager_test.go, pkg/pipelines/down.go, pkg/pipelines/down_test.go
We were previously not properly waiting for resources to terminate as expected. This change will both wait for cleanup kustomizations to complete, and wait for termination of resources when kustomizations are deleted.
=> fix(blueprint): Wait for kustomizations to complete and their resources to terminate

pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/kubernetes/kubernetes_manager.go, pkg/kubernetes/kubernetes_manager_test.go
Forward slashes were making it in to the paths given to the generated cleanup kustomizations on Windows. Fixed. Also fails fast for ArtifactFailed scenarios.
=> fix(cleanup): Fix kustomize paths on Windows

pkg/blueprint/blueprint_handler_helper_test.go, pkg/config/config_handler.go, pkg/config/config_handler_test.go, pkg/config/mock_config_handler.go, pkg/config/mock_config_handler_test.go, pkg/config/yaml_config_handler.go, pkg/pipelines/check_test.go, pkg/pipelines/env_test.go, pkg/pipelines/init.go, pkg/pipelines/pipeline.go, pkg/template/jsonnet_template.go
A default configuration was loaded on top of the local `windsor.yaml` config. This caused incorrect template values on running `windsor init`.
A few areas contributed to this. To remediate, the `--reset` logic that prevented file config loading has been removed as it is no longer the desired functionality. Furthermore, we ensure that we only load a default configuration if an existing context config has not loaded.
=> fix(config): Ensure proper config loading order

pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/generators/kustomize_generator.go, pkg/generators/kustomize_generator_test.go, pkg/template/jsonnet_template.go, pkg/template/jsonnet_template_test.go
All post build values are now defined in a single `contexts/<context>/kustomize/values.yaml` file. Only permits one nested level of values mapping to individual kustomizations. The `common` key permits including post build values across all kustomizations.
=> feat(blueprint): Centralize post build variables to a single values.yaml file

cmd/build_id.go, cmd/build_id_test.go, cmd/root.go, pkg/blueprint/blueprint_handler.go, pkg/blueprint/blueprint_handler_test.go, pkg/env/windsor_env.go, pkg/env/windsor_env_test.go, pkg/pipelines/build_id.go, pkg/pipelines/build_id_test.go, pkg/pipelines/pipeline.go, pkg/pipelines/shims.go
A build ID can be generated by running `windsor build-id --new`. This mechanism creates a `BUILD_ID` environment variable, and injects a `BUILD_ID` as a post build in the kubernetes cluster.
Bulid IDs are formatted `YYMMDD.RND.#`
Which includes a date, random ID, and an incrementing integer. This mechanism can be used for tagging and deploying images to the local development cluster. Each `windsor install` will trigger an update to the build ID if it has changed, triggering a redeploy.
=> feat(cmd): Add windsor build-id command

api/v1alpha2/config/config.go, api/v1alpha2/config/config_test.go, api/v1alpha2/config/providers/aws/aws.go, api/v1alpha2/config/providers/aws/aws_test.go, api/v1alpha2/config/providers/azure/azure.go, api/v1alpha2/config/providers/azure/azure_test.go, api/v1alpha2/config/providers/providers.go, api/v1alpha2/config/providers/providers_test.go, api/v1alpha2/config/secrets/onepassword/onepassword.go, api/v1alpha2/config/secrets/onepassword/onepassword_test.go, api/v1alpha2/config/secrets/secrets.go, api/v1alpha2/config/secrets/secrets_test.go, api/v1alpha2/config/terraform/terraform.go, api/v1alpha2/config/terraform/terraform_test.go, api/v1alpha2/config/workstation/cluster/cluster.go, api/v1alpha2/config/workstation/cluster/cluster_test.go, api/v1alpha2/config/workstation/dns/dns.go, api/v1alpha2/config/workstation/dns/dns_test.go, api/v1alpha2/config/workstation/git/git.go, api/v1alpha2/config/workstation/git/git_test.go, api/v1alpha2/config/workstation/localstack/localstack.go, api/v1alpha2/config/workstation/localstack/localstack_test.go, api/v1alpha2/config/workstation/network/network.go, api/v1alpha2/config/workstation/network/network_test.go, api/v1alpha2/config/workstation/registries/registries.go, api/v1alpha2/config/workstation/registries/registries_test.go, api/v1alpha2/config/workstation/vm/vm.go, api/v1alpha2/config/workstation/vm/vm_test.go, api/v1alpha2/config/workstation/workstation.go, api/v1alpha2/config/workstation/workstation_test.go
The v1alpha2 schema represents the next structure of the `windsor.yaml` file. The major change involves creating a dedicated block for configuring the workstation. Now, workstations could be considered more of a common resource that does not strictly belong to a context. If a local workstation exists, contexts can provision resources on it and leverage its services.
Other changes involve organizing cloud provider blocks, and simplifying Terraform backend config.
Some minor changes like dropping "provider" and "id" are in preparation for a blueprint focused `values.yaml` feature in the future.
=> refactor(config): Begin designing v1alpha2 config schema

pkg/generators/terraform_generator.go, pkg/generators/terraform_generator_test.go
When processing templated tfvars files for a blueprint, these files are now generated as `terraform.tfvars` files directly in the `.tf_modules` folder along with the generated module shims. Now these generated input variables act as the base vars when deploying from a template. The corresponding `terraform/xyz/*.tfvars` files are now only necessary for overrides or parameterizing user-defined terraform components.
=> refactor(generator): Generates templated tfvars to tf_modules vs. context folder

api/v1alpha1/blueprint_types.go, api/v1alpha1/blueprint_types_test.go, pkg/blueprint/blueprint_handler_test.go, pkg/blueprint/defaults.go
The Authors field isn't valuable here and is better represented within OCI metadata.
=> chore(blueprint): Remove Authors field

api/v1alpha1/feature_types.go, api/v1alpha1/feature_types_test.go
Sets up the new Feature type, which behaves as a trimmed down conditional fragment of a blueprint.
=> chore(blueprint): Add blueprint Feature type

go.mod, go.sum, pkg/blueprint/feature_evaluator.go, pkg/blueprint/feature_evaluator_test.go
Adds the feature evaluator to the blueprint package. This uses the simple Go expr language to evaluate simple conditionals based on context data. This will ultimately be used for blueprint Feature composition.
=> feat(blueprint): Add feature evaluator

api/v1alpha1/blueprint_types.go, api/v1alpha1/blueprint_types_test.go
Adds a strategic merge for merging features / blueprints. This allows for components to be merge in a manner that:
1. Keeps related components close together
2. Orders components based on the `dependsOn` field
3. Alphabetizes merged sub-components
=> chore(blueprint): Add strategic merge for merging blueprints
