windsorcli/cli

- .github/workflows/ci.yaml
Added github paths to input parameters of the go build command
> Version command fix

- .github/renovate.json
Making renovate update and merge
> Renovate updates

- pkg/stack/windsor_stack.go
- pkg/stack/windsor_stack_test.go
Improves Terraform messages so we know which stages are being deployed.
> Improve Terraform messaging

- pkg/stack/windsor_stack.go
- pkg/stack/windsor_stack_test.go
> Improved terraform messaging

- pkg/blueprint/templates/local.jsonnet
updated core reference and add renovate support
> Updated core reference

- api/v1alpha1/blueprint_types.go
Fixes an issue in which the ordering of kustomize components occasionally get re-arranged.
> Enforce ordering of kustomize components

- aqua.yaml
Add helm to the aqua.yaml file
> Add helm to the aqua.yaml file

- pkg/blueprint/templates/local.jsonnet
There are some tricks to configuring registry mirrors, especially re: `docker.io`, `registry-1.docker.io`, and how Talos registry mirror configuration works. This fixes the issue of not properly storing docker hub images in cache.
> Implement proper handling of local config of registry mirror

- docs/guides/environment-injection.md
- docs/guides/local-workstation.md
- docs/quick-start.md
- docs/reference/blueprint.md
- docs/reference/configuration.md
- docs/tutorial/hello-world.md
> 0.4.0 Documentation

- docs/tutorial/hello-world.md
Fixed the dockerfile block in the hello-world tutorial.
> dockerfile-fix

- pkg/secrets/op_cli_secrets_provider.go
- pkg/secrets/op_cli_secrets_provider_test.go
- pkg/secrets/secrets_provider.go
- pkg/secrets/secrets_provider_test.go
There were several edge cases the path parser couldn't handle. This implements a more robust parser.
> Expanded secrets path parser

- README.md
- docs/docker-compose.yaml
- docs/guides/contexts.md
- docs/guides/environment-injection.md
- docs/guides/kustomize.md
- docs/guides/local-workstation.md
- docs/guides/secrets.md
- docs/guides/terraform.md
- docs/index.md
- docs/reference/blueprint.md
- docs/reference/configuration.md
- docs/reference/contexts.md
- docs/security/secrets.md
- docs/security/trusted-folders.md
- docs/tutorial/hello-world.md
Includes documentation on new v0.5.0 features.
> 0.5.0 Documentation

- pkg/constants/constants.go
- pkg/env/terraform_env.go
- pkg/env/terraform_env_test.go
- pkg/env/windsor_env.go
- pkg/shell/docker_shell.go
- pkg/shell/docker_shell_test.go
- pkg/shell/shell_test.go
- pkg/shell/unix_shell.go
- pkg/shell/windows_shell.go
- pkg/stack/stack.go
- pkg/stack/stack_test.go
- pkg/stack/windsor_stack.go
- pkg/stack/windsor_stack_test.go
When running `windsor up` and `WINDSOR_EXEC_MODE=container`, the terraform commands will be executed in the container environment.
> Execute windsor up terraform commands via container exec mode

- pkg/network/darwin_network.go
We weren't sufficiently checking if the DNS resolver file was already set, leading to asking for `sudo` frequently. We now properly check before running privileged commands.
> Fix idempotency when configuring network on darwin

- pkg/env/docker_env.go
We set default values for `DOCKER_HOST` within the CLI. We would prefer to use this environment variable if it is set, preferring it over our internal defaults.
> Default to use DOCKER_HOST if defined

- api/v1alpha1/blueprint_types.go
- cmd/down.go
- cmd/down_test.go
- cmd/install.go
- cmd/install_test.go
- cmd/up.go
- cmd/up_test.go
- pkg/blueprint/blueprint_handler.go
- pkg/blueprint/blueprint_handler_helper_test.go
- pkg/blueprint/blueprint_handler_private_test.go
- pkg/blueprint/blueprint_handler_test.go
- pkg/blueprint/mock_blueprint_handler.go
- pkg/blueprint/mock_blueprint_handler_test.go
- pkg/constants/constants.go
- pkg/stack/windsor_stack.go
- Add cleanup support for kustomizations in Down method
- Update Down method to handle kustomization cleanup
- Add kustomization cleanup to cleanup process
- Update test coverage for kustomization cleanup
> feat(install): add cleanup support for kustomizations

- pkg/env/windsor_env.go
- pkg/env/windsor_env_test.go
• Add WINDSOR_CONTEXT_ID to managed environment variables
> feat: add WINDSOR_CONTEXT_ID environment variable

- .github/workflows/ci.yaml
Follow guidelines to optimize Windows I/O performance during CI operations by using the D: drive.
> chore(ci): Enhance windows CI performance

- cmd/init.go
- cmd/init_test.go
- pkg/pipelines/init.go
- pkg/pipelines/init_test.go
Refactors `windsor init` to execute using the pipeline architecture.
> refactor(pipeline): Refactor init to use pipeline structure

- pkg/terraform/oci_module_resolver.go
- pkg/terraform/oci_module_resolver_test.go
Adds a terraform module resolver capable of extracting terraform modules from an OCI artifact.
> refactor(terraform): Add terraform oci module resolver

- pkg/pipelines/pipeline.go
- pkg/pipelines/pipeline_test.go
- pkg/template/jsonnet_template.go
Included new with* functions in the pipeline to cover the addition of terraform module resolvers and template renderers
> refactor(pipeline): Add withTerraformResolvers and withTemplateRenderer

- pkg/pipelines/artifact.go
- pkg/pipelines/artifact_test.go
- pkg/pipelines/pipeline.go
The artifact pipeline can run in both a "bundle" and "push" mode. This will be implemented by respective commands in other PRs.
> refactor(pipeline): Create artifact pipeline

- pkg/artifact/artifact.go
- pkg/artifact/artifact_test.go
We need to know the OCI url and name attributes by templateData consumers. This will be used later to template blueprints with proper `source` references.
> refactor(artifact): Include correct metadata with templates returned from artifact

- pkg/kubernetes/kubernetes_manager_test.go
- pkg/kubernetes/mock_kubernetes_manager_test.go
Test coverage was lacking in the kubernetes manager. Increased test coverage by covering missing lines in functions that check node readiness.
> test(kubernetes): Improve test coverage

- pkg/blueprint/blueprint_handler.go
When we apply cleanup kustomizations, we need to give them ample time to succeed. We also need to detect when they fail and exit.
> fix(down): Improve timing and  robustness of cleanup kustomizations
